version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"
    commit-message:
      prefix: ⬆

updates:
  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    patterns: ['*']
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      python-packages:
        patterns:
          - "*"
    commit-message:
      prefix: ⬆
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "infrastructure"
    patterns: ['*']
