queue_rules:
  - name: default
    update_method: rebase
    branch_protection_injection_mode: merge
    queue_conditions:
      - and:
        - check-success = ci
merge_queue:
  max_parallel_checks: 1
