queue_rules:
  - name: default
    update_method: rebase
    branch_protection_injection_mode: merge
    update_bot_account: openebs-ci
merge_queue:
  max_parallel_checks: 1
pull_request_rules:
  - name: a1
    conditions:
      - title~=\(backport 1\)$
    actions:
      label:
        add:
          - kind/backport1
      review:
        type: APPROVE
        message: "Automatically approved backport PR"
  - name: a2
    conditions:
      - title~=\(backport\)
    actions:
      label:
        add:
          - kind/backport2
  - name: a3
    conditions:
      - title~=\(backport\)$
    actions:
      label:
        add:
          - kind/backport3
  - name: a4
    conditions:
      - title~=\(backport \#1\)$
    actions:
      label:
        add:
          - kind/backport4
  - name: a5
    conditions:
      - title~=\(backport \#[0-9]+\)$
    actions:
      label:
        add:
          - kind/backport5
  - name: a6
    conditions:
      - author=mergify[bot]
      - title~=\(backport \#[0-9]+\)$
    actions:
      label:
        add:
          - kind/backport6
