# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'internal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0einternal.proto\";\n\x14\x45xpandRawFileRequest\x12\x11\n\tvolume_id\x18\x01 \x01(\t\x12\x10\n\x08new_size\x18\x02 \x01(\x03\"R\n\x15\x45xpandRawFileResponse\x12\x13\n\x0bis_attached\x18\x01 \x01(\x08\x12$\n\x06status\x18\x02 \x01(\x0e\x32\x14.ExpandRawFileStatus*5\n\x13\x45xpandRawFileStatus\x12\x06\n\x02OK\x10\x00\x12\x16\n\x12RESOURCE_EXHAUSTED\x10\x01\x32J\n\x08Internal\x12>\n\rExpandRawFile\x12\x15.ExpandRawFileRequest\x1a\x16.ExpandRawFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXPANDRAWFILESTATUS']._serialized_start=163
  _globals['_EXPANDRAWFILESTATUS']._serialized_end=216
  _globals['_EXPANDRAWFILEREQUEST']._serialized_start=18
  _globals['_EXPANDRAWFILEREQUEST']._serialized_end=77
  _globals['_EXPANDRAWFILERESPONSE']._serialized_start=79
  _globals['_EXPANDRAWFILERESPONSE']._serialized_end=161
  _globals['_INTERNAL']._serialized_start=218
  _globals['_INTERNAL']._serialized_end=292
# @@protoc_insertion_point(module_scope)
