# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import internal_pb2 as internal__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in internal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InternalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExpandRawFile = channel.unary_unary(
                '/Internal/ExpandRawFile',
                request_serializer=internal__pb2.ExpandRawFileRequest.SerializeToString,
                response_deserializer=internal__pb2.ExpandRawFileResponse.FromString,
                _registered_method=True)


class InternalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ExpandRawFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InternalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExpandRawFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ExpandRawFile,
                    request_deserializer=internal__pb2.ExpandRawFileRequest.FromString,
                    response_serializer=internal__pb2.ExpandRawFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Internal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Internal', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Internal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ExpandRawFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Internal/ExpandRawFile',
            internal__pb2.ExpandRawFileRequest.SerializeToString,
            internal__pb2.ExpandRawFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
