# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'internal.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0einternal.proto\x1a\x19google/protobuf/any.proto\";\n\x14\x45xpandRawFileRequest\x12\x11\n\tvolume_id\x18\x01 \x01(\t\x12\x10\n\x08new_size\x18\x02 \x01(\x03\"R\n\x15\x45xpandRawFileResponse\x12\x13\n\x0bis_attached\x18\x01 \x01(\x08\x12$\n\x06status\x18\x02 \x01(\x0e\x32\x14.ExpandRawFileStatus\"c\n\x11GetRawFileRequest\x12\x11\n\tvolume_id\x18\x01 \x01(\t\x12\x11\n\twith_data\x18\x02 \x01(\x08\x12\x18\n\x0bsnapshot_id\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_snapshot_id\"\x9e\x01\n\x12GetRawFileResponse\x12\x33\n\x08metadata\x18\x01 \x03(\x0b\x32!.GetRawFileResponse.MetadataEntry\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x1a\x45\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01*5\n\x13\x45xpandRawFileStatus\x12\x06\n\x02OK\x10\x00\x12\x16\n\x12RESOURCE_EXHAUSTED\x10\x01\x32\x81\x01\n\x08Internal\x12>\n\rExpandRawFile\x12\x15.ExpandRawFileRequest\x1a\x16.ExpandRawFileResponse\x12\x35\n\nGetRawFile\x12\x12.GetRawFileRequest\x1a\x13.GetRawFileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'internal_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETRAWFILERESPONSE_METADATAENTRY']._loaded_options = None
  _globals['_GETRAWFILERESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EXPANDRAWFILESTATUS']._serialized_start=452
  _globals['_EXPANDRAWFILESTATUS']._serialized_end=505
  _globals['_EXPANDRAWFILEREQUEST']._serialized_start=45
  _globals['_EXPANDRAWFILEREQUEST']._serialized_end=104
  _globals['_EXPANDRAWFILERESPONSE']._serialized_start=106
  _globals['_EXPANDRAWFILERESPONSE']._serialized_end=188
  _globals['_GETRAWFILEREQUEST']._serialized_start=190
  _globals['_GETRAWFILEREQUEST']._serialized_end=289
  _globals['_GETRAWFILERESPONSE']._serialized_start=292
  _globals['_GETRAWFILERESPONSE']._serialized_end=450
  _globals['_GETRAWFILERESPONSE_METADATAENTRY']._serialized_start=381
  _globals['_GETRAWFILERESPONSE_METADATAENTRY']._serialized_end=450
  _globals['_INTERNAL']._serialized_start=508
  _globals['_INTERNAL']._serialized_end=637
# @@protoc_insertion_point(module_scope)
