name: CI
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  cci:
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: CI succeeded
        run: exit 0
