name: CI
on:
  merge_group:
  pull_request:

jobs:
  a:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: a
        run: echo "a" 
  b:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: a
        run: echo "a" 

