name: Container Images
on:
  push:
    branches:
      - develop
      - 'release/**'
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
        default: docker.io
      namespace:
        required: false
        type: string
        default: openebs

env:
  CI: 1

jobs:
  image-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@v19
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            network=host
      - name: Pre-populate nix-shell
        run: |
          export NIX_PATH=nixpkgs=$(jq '.nixpkgs.url' nix/sources.json -r)
          echo "NIX_PATH=$NIX_PATH" >> $GITHUB_ENV
          nix-shell --run "echo"
      - name: Build
        env:
          CI_TEST: "false"
          CI_IMAGE_NS: ${{ inputs.namespace }}
          DNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DPASS: ${{ secrets.DOCKERHUB_TOKEN }}
          DREG: ${{ inputs.registry }}
        run: nix-shell --run ".ci/build.sh"
